sudo: required
language: java

services:
  - docker

jdk:
  - openjdk8
#  - openjdk11

matrix:
  allow_failures:
    - jdk: openjdk11

before_install:
  # Disable services enabled by default
  - sudo service mysql stop
  - sudo /etc/init.d/postgresql stop

  # Run my databases in the background
  - docker-compose -f docker/docker-compose-travis.yml up -d

install:
  - TERM=dumb ./gradlew assemble

#before_script:
#  - sleep 15

script:
  - TERM=dumb ./gradlew testAll codeCoverageReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)

#after_failure:
#  - TERM=dumb ./gradlew build testAll --stacktrace
